# Generated by Django 4.1.7 on 2023-03-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('Size', models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'X-LARGE'), ('XXL', 'XX-LARGE')], max_length=128)),
                ('price', models.IntegerField()),
                ('product_offer', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
            ],
        ),
    ]
